name: test_all_files

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
    branches: 
      - development

jobs:
  Run_Unit_Tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Install Go
        uses: actions/setup-go@v5
      - name: checkout
        uses: actions/checkout@v4
      - name: Download Go dependencies
        run: go mod tidy
      - name: "Run Unit Tests"
        run:  go test -v ./...

